#!/bin/bash

# Quick Guide: Adding Mentor Photos to VayuKavach Team Section
# ==============================================================

echo ""
echo "📸 ADDING MENTOR PHOTOS - QUICK GUIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show what we need
echo "🎯 PHOTOS NEEDED:"
echo ""
echo "   1. Dr. Aftab Ahmed Ansari → Save as: dr-aftab.jpg"
echo "   2. Dr. Praveen Bansal → Save as: dr-praveen.jpg"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Method 1: Direct copy
echo "📋 METHOD 1: COPY PHOTOS DIRECTLY"
echo ""
echo "If you have the photos ready:"
echo ""
echo "1. Make sure photos are named EXACTLY:"
echo "   • dr-aftab.jpg (or .png or .jpeg)"
echo "   • dr-praveen.jpg (or .png or .jpeg)"
echo ""
echo "2. Copy them to the team folder:"
echo "   cp /path/to/dr-aftab.jpg \"$(pwd)/public/team/\""
echo "   cp /path/to/dr-praveen.jpg \"$(pwd)/public/team/\""
echo ""
echo "   OR simply drag & drop into:"
echo "   📁 $(pwd)/public/team/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Method 2: Use Finder
echo "📋 METHOD 2: USING FINDER (EASIEST)"
echo ""
echo "1. Open Finder"
echo "2. Press Cmd+Shift+G"
echo "3. Paste this path:"
echo "   $(pwd)/public/team"
echo "4. Press Enter"
echo "5. Drag your mentor photos into this folder"
echo "6. Rename them to:"
echo "   • dr-aftab.jpg"
echo "   • dr-praveen.jpg"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Method 3: Terminal command
echo "📋 METHOD 3: TERMINAL COMMAND"
echo ""
echo "If photos are in Downloads:"
echo ""
echo "cd \"$(pwd)\""
echo "cp ~/Downloads/dr-aftab.jpg public/team/"
echo "cp ~/Downloads/dr-praveen.jpg public/team/"
echo ""
echo "Or if they have different names:"
echo ""
echo "cp ~/Downloads/aftab-photo.jpg public/team/dr-aftab.jpg"
echo "cp ~/Downloads/praveen-photo.jpg public/team/dr-praveen.jpg"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Photo specs
echo "📐 PHOTO SPECIFICATIONS:"
echo ""
echo "   ✅ Size: 512×512px recommended (min 400×400px)"
echo "   ✅ Format: JPG, PNG, or JPEG"
echo "   ✅ Aspect Ratio: 1:1 (square)"
echo "   ✅ File Size: Under 500KB"
echo "   ✅ Quality: Professional headshot"
echo "   ✅ Background: Solid or blurred preferred"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# After adding
echo "🚀 AFTER ADDING PHOTOS:"
echo ""
echo "1. Verify they're added:"
echo "   ./setup-team-images.sh"
echo ""
echo "2. Test locally:"
echo "   npm run dev"
echo "   Open: http://localhost:3000"
echo ""
echo "3. Deploy to Vercel:"
echo "   git add public/team/dr-*.jpg"
echo "   git commit -m \"Add mentor photos\""
echo "   git push origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Open folder option
echo "💡 TIP: Want to open the team folder now?"
echo ""
echo "Run this command to open in Finder:"
echo "   open public/team"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Where are your photos?
echo "❓ WHERE ARE YOUR MENTOR PHOTOS?"
echo ""
echo "Tell me where they are, and I'll help you copy them!"
echo ""
echo "Examples:"
echo "   • In Downloads folder"
echo "   • On Desktop"
echo "   • In a specific folder"
echo "   • Need to download them first"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
